---
- name: Apply build role
  gather_facts: no
  hosts: "{{ kit_number }}"
  tasks:
  - set_fact:
      start_time: "{{ lookup('pipe', 'date +%Y%m%d%H%M%S') }}"
    delegate_to: localhost
    delegate_facts: true
