---
- name: checks devices for specific snmp user
  gather_facts: no
  hosts: routers
  connection: network_cli
  tasks:
    - name: register snmp user output as variable
      ios_command:
        - show snmp user
      register: stuff

    - name: debug the output
      debug:
        msg: stuff.stdout