---
- name: configure snmp for routers
  gather_facts: no
  hosts: routers
  connection: network_cli
  tasks:
    - name: register output as a variable
      ios_command:
        commands: show snmp user
      register: stuff

    - name: debug the output
      debug:
        msg: SUCCESSFUL
      when:
        - 'stuff.stdout_lines.Group-name == "test_group"'