---
- name: This playbook will convert a traditional eigrp config to named mode
  gather_facts: no
  hosts: vIOS
  connection: network_cli
  vars:
    head_commands: []
    general_commands: []
    topology_base_commands: []
    non_passive_interfaces: []

  tasks:
    - name: gather necessary info and store into variables
      ios_command:
        commands: show run | s router eigrp
      register: eigrp_config

    - name: Find and store first eigrp statements for any AS
      set_fact:
        head_commands: "{{ head_commands }} + [ '{{ item }}' ]"
      with_items: "{{ eigrp_config.stdout_lines[0] }}"
      when: "'router eigrp' in item"

    - name: Find and store general eigrp commands
      set_fact:
        general_commands: "{{ general_commands }} + [ '{{ item }}' ]"
      with_items: "{{ eigrp_config.stdout_lines[0] }}"
      when: ('network' in item) or (item[:6] == ' eigrp')

    - name: Find and store topology base commands
      set_fact:
        topology_base_commands: "{{ topology_base_commands }} + [ '{{ item }}' ]"
      with_items: "{{ eigrp_config.stdout_lines[0] }}"
      when: ('distribute-list' in item) or ('redistribute' in item)

    - name: Find and store interfaces that are supposed to be no-passive
      set_fact:
        correct: "'yes' if ' passive-interface default' in eigrp_config.stdout_lines[0] else 'no'"
        non_passive_interfaces: "{{ non_passive_interfaces }} + [ '{{ item.split()[2:] }}' ]"
      with_items: "{{ eigrp_config.stdout_lines[0] }}"
      when:
        - "' no passive-interface' in item"

    - name: display new variable
      debug: var=non_passive_interfaces