---
- name: This playbook will convert a traditional eigrp config to named mode
  gather_facts: no
  hosts: vIOS
  connection: network_cli
  vars:
    general_commands: []
  tasks:
    - name: gather necessary info and store into variables
      ios_command:
        commands: show run | s router eigrp
      register: eigrp_config

    - name: store new variables
      set_fact:
        general_commands: "{{ general_commands }} + [ '{{ item }}' ]"
      with_items: "{{ eigrp_config.stdout_lines[0] }}"
      when: ('network' in item) or (item[:6] == ' eigrp')


    - name: display new variable
      debug: var=general_commands