---
- name: This playbook will convert a traditional eigrp config to named mode
  gather_facts: no
  hosts: routers
  connection: network_cli
  tasks:
    - name: gather necessary info and store into variables
      ios_command:
        commands: show run | s router eigrp
      register: eigrp_config

- name: create new list
  gather_facts: no
  hosts: routers
  connection: local
  vars:
    - general_commands: '{{ [ line for line in eigrp_config.stdout_lines[0] if line.startswith(("eigrp","network")) ] }}'
  
  tasks:
    - name: show output
      debug: var=general_commands