---
- name: This playbook will convert a traditional eigrp config to named mode
  gather_facts: no
  hosts: routers
  connection: network_cli
  vars:
    general_commands: []
    topology_base_commands: []
    non_passive_interfaces: []

  tasks:
    - name: gather necessary info and store into variables
      ios_command:
        commands: show run | s router eigrp
      register: eigrp_config