---
- name: This playbook will convert a traditional eigrp config to named mode
  gather_facts: no
  hosts: vIOS
  connection: network_cli
  tasks:
    - name: gather necessary info and store into variables
      ios_command:
        commands: show run | s router eigrp
      register: eigrp_config

    - name: store new variables
      set_fact:
        networks: '{{ eigrp_config.stdout_lines[0] | select("match", "network*") }}'

    - name: display new variable
      debug: var=networks