---
- name: This playbook will convert a traditional eigrp config to named mode
  gather_facts: no
  hosts: vIOS
  connection: network_cli
  tasks:
    - name: gather necessary info and store into variables
      ios_command:
        commands: show run | s router eigrp
      register: eigrp_config

    - name: store aspects in variables
      vars:
        - first_line: "{{ eigrp_config.stdout_lines[0][0] | upper }}"

    - name: hopefully display the new variable
      debug: var=first_line