---
- name: This playbook will convert a traditional eigrp config to named mode
  gather_facts: no
  hosts: vIOS
  connection: network_cli
  tasks:
    - name: gather necessary info and store into variables
      ios_command:
        commands: show run | s router eigrp
      register: eigrp_config

    - name: create the directory to store the files
      file:
        path: /home/jake/output/
        state: directory
        mode: 777
      delegate_to: localhost

    - name: create new templated config
      template:
        src: test.j2
        dest: /home/jake/output/named_eigrp.cfg
      register: output

    - name: hopefully display the output
      debug: var=output