---
- name: this will gather and use facts from an IOS device
  hosts: vIOS
  gather_facts: no
  connection: network_cli

  tasks:
    - name: gather ios facts
      ios_facts:
        gather_subset: interfaces
      register: output

    - name: debug output
      debug: msg={{ output }}