---
- name: this will gather and use facts from an IOS device
  hosts: vIOS
  gather_facts: no
  connection: network_cli
  vars:
    - interfaces: []

  tasks:
    - name: gather ios facts
      ios_facts:
        gather_subset: interfaces
      register: output

    - name: create output
      set_fact:
        interfaces: "{{ interfaces }} + [ '{{ item.value }}' ]"
      loop: "{{ output.ansible_facts.ansible_net_interfaces | dict2items }}"

    - name: show output
      debug: var=interfaces