---
- name: Mail Push
  gather_facts: no
  hosts: localhost
  tasks:
  - name: zip the config files
    archive:
      path: "{{ playbook_dir }}/{{ start_time }}"
      dest: "{{ playbook_dir }}/{{ start_time }}.zip"
      format: zip
    delegate_to: localhost
    
  - name: Email when complete
    mail:
      host: 192.168.58.160
      port: 25
      from: jake@localhost
      to: "{{ user_email }}"
      subject: complete configs for "{{ kit_number | join(", ")}}"
      body: 'congrats, it worked biatch'
    delegate_to: localhost
