---
- name: Mail Push
  gather_facts: no
  hosts: localhost
  tasks:
  - name: zip the config files
    archive:
      path: "{{ playbook_dir }}/{{ start_time }}"
      dest: "{{ playbook_dir }}/{{ start_time }}.zip"
      format: zip
    delegate_to: localhost
  
  - name: see if the files actually updated
    debug:
      msg: "System {{ inventory_hostname }} is using {{ mail_port }}"
    
  - name: Email when complete
    mail:
      host: smtp.gmail.com
      port: "{{ mail_port }}"
      username: jake.richman95@gmail.com
      password: 1qaz2wsx!QAZ@WSX1
      to: "{{ user_email }}"
      subject: complete configs for "{{ kit_number | join(", ")}}"
      body: 'congrats, it worked biatch'
