---
- name: Mail Push
  gather_facts: no
  hosts: localhost
  tasks:
  - name: zip the config files
    archive:
      path: "{{ playbook_dir }}/{{ start_time }}"
      dest: "{{ playbook_dir }}/{{ start_time }}.zip"
      format: zip
    delegate_to: localhost
    
  - name: Email when complete
    mail:
      host: smtp.mail.yahoo.com
      port: 465
      username: jakerichman99@yahoo.com
      password: 1234567Uj
      to: "{{ user_email }}"
      subject: complete configs for "{{ kit_number | join(", ")}}"
      body: 'congrats, it worked biatch'
    delegate_to: localhost
